
server.port=${PORT:8080}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:h2:file:${H2_DB_PATH:./data/arms};MODE=MySQL;DATABASE_TO_LOWER=TRUE;NON_KEYWORDS=USER,START,END;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.sql.init.mode=never
spring.web.resources.add-mappings=true
spring.jpa.open-in-view=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console