CREATE TABLE IF NOT EXISTS "user" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS airplane (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    airline VARCHAR(255),
    flight_number VARCHAR(255) UNIQUE,
    aircraft_model VARCHAR(255),
    "start" VARCHAR(255),
    "end" VARCHAR(255),
    departure_time VARCHAR(50),
    arrival_time VARCHAR(50),
    avl_seat INTEGER NOT NULL,
    num_of_km DOUBLE PRECISION NOT NULL,
    price DOUBLE PRECISION NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_airplane_route ON airplane ("start", "end");

CREATE TABLE IF NOT EXISTS booking (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_reference VARCHAR(255) UNIQUE,
    b_start VARCHAR(255),
    b_end VARCHAR(255),
    user_email VARCHAR(255),
    airline VARCHAR(255),
    flight_number VARCHAR(255),
    aircraft_model VARCHAR(255),
    departure_time VARCHAR(50),
    arrival_time VARCHAR(50),
    class_type VARCHAR(50),
    seat_numbers VARCHAR(255),
    b_num_ofseat INTEGER NOT NULL,
    price DOUBLE PRECISION NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_booking_user_email ON booking (user_email);
CREATE INDEX IF NOT EXISTS idx_booking_route ON booking (b_start, b_end);

MERGE INTO airplane (
    airline,
    flight_number,
    aircraft_model,
    "start",
    "end",
    departure_time,
    arrival_time,
    avl_seat,
    num_of_km,
    price
) KEY (flight_number) VALUES
    ('Air India', 'AI 401', 'Airbus A320neo', 'Delhi', 'Mumbai', '06:15 AM', '08:25 AM', 168, 1148.0, 6200.0),
    ('IndiGo', '6E 402', 'Airbus A321neo', 'Mumbai', 'Delhi', '09:10 AM', '11:20 AM', 186, 1148.0, 6100.0),
    ('Vistara', 'UK 403', 'Boeing 737-800', 'Delhi', 'Jaipur', '07:30 AM', '08:35 AM', 142, 241.0, 3200.0),
    ('SpiceJet', 'SG 404', 'Boeing 737', 'Jaipur', 'Delhi', '06:40 PM', '07:45 PM', 128, 241.0, 3100.0),
    ('Akasa Air', 'QP 405', 'Boeing 737 MAX 8', 'Ahmedabad', 'Mumbai', '08:05 AM', '09:20 AM', 154, 444.0, 3900.0),
    ('IndiGo', '6E 406', 'Airbus A320neo', 'Mumbai', 'Goa', '01:15 PM', '02:30 PM', 172, 425.0, 4200.0),
    ('Air India Express', 'IX 407', 'Boeing 737-800', 'Goa', 'Bangalore', '03:20 PM', '04:45 PM', 136, 463.0, 4500.0),
    ('Vistara', 'UK 408', 'Airbus A320neo', 'Bangalore', 'Hyderabad', '07:00 AM', '08:10 AM', 160, 502.0, 4100.0),
    ('IndiGo', '6E 409', 'Airbus A320neo', 'Hyderabad', 'Chennai', '10:35 AM', '11:50 AM', 174, 515.0, 4300.0),
    ('Air India', 'AI 410', 'Airbus A321', 'Chennai', 'Bangalore', '05:45 PM', '06:55 PM', 158, 290.0, 3600.0),
    ('Akasa Air', 'QP 411', 'Boeing 737 MAX 8', 'Bangalore', 'Kochi', '08:25 PM', '09:35 PM', 162, 368.0, 3900.0),
    ('Air India Express', 'IX 412', 'Boeing 737-800', 'Kochi', 'Thiruvananthapuram', '06:30 AM', '07:15 AM', 132, 195.0, 2800.0),
    ('IndiGo', '6E 413', 'Airbus A320neo', 'Thiruvananthapuram', 'Chennai', '09:30 AM', '11:00 AM', 168, 620.0, 5200.0),
    ('Vistara', 'UK 414', 'Airbus A320neo', 'Chennai', 'Kolkata', '12:40 PM', '03:05 PM', 156, 1366.0, 7100.0),
    ('Air India', 'AI 415', 'Airbus A320neo', 'Kolkata', 'Guwahati', '07:20 AM', '08:35 AM', 150, 528.0, 4600.0),
    ('IndiGo', '6E 416', 'Airbus A320neo', 'Guwahati', 'Imphal', '10:10 AM', '11:05 AM', 144, 269.0, 3400.0),
    ('Alliance Air', '9I 417', 'ATR 72-600', 'Imphal', 'Agartala', '02:15 PM', '03:35 PM', 62, 313.0, 3800.0),
    ('SpiceJet', 'SG 418', 'Boeing 737', 'Agartala', 'Kolkata', '05:10 PM', '06:20 PM', 126, 327.0, 3700.0),
    ('Air India', 'AI 419', 'Airbus A320neo', 'Kolkata', 'Patna', '08:45 AM', '09:55 AM', 152, 472.0, 4100.0),
    ('IndiGo', '6E 420', 'Airbus A320neo', 'Patna', 'Lucknow', '12:25 PM', '01:45 PM', 166, 439.0, 4300.0),
    ('Vistara', 'UK 421', 'Airbus A320neo', 'Lucknow', 'Delhi', '06:05 PM', '07:20 PM', 154, 419.0, 4000.0),
    ('IndiGo', '6E 422', 'Airbus A321neo', 'Delhi', 'Srinagar', '05:50 AM', '07:20 AM', 180, 643.0, 5600.0),
    ('Air India', 'AI 423', 'Airbus A320neo', 'Srinagar', 'Jammu', '09:05 AM', '09:45 AM', 148, 148.0, 2600.0),
    ('Alliance Air', '9I 424', 'ATR 72-600', 'Jammu', 'Chandigarh', '11:15 AM', '12:15 PM', 66, 344.0, 3300.0),
    ('Vistara', 'UK 425', 'Airbus A320neo', 'Chandigarh', 'Dehradun', '04:05 PM', '05:00 PM', 140, 205.0, 3100.0),
    ('IndiGo', '6E 426', 'Airbus A320neo', 'Dehradun', 'Delhi', '07:15 PM', '08:10 PM', 168, 207.0, 3000.0),
    ('Air India', 'AI 427', 'Airbus A320neo', 'Delhi', 'Bhopal', '06:55 AM', '08:20 AM', 156, 587.0, 4800.0),
    ('IndiGo', '6E 428', 'Airbus A320neo', 'Bhopal', 'Indore', '09:40 AM', '10:30 AM', 160, 170.0, 2700.0),
    ('Akasa Air', 'QP 429', 'Boeing 737 MAX 8', 'Indore', 'Pune', '01:05 PM', '02:25 PM', 158, 507.0, 4400.0),
    ('SpiceJet', 'SG 430', 'Boeing 737', 'Pune', 'Nagpur', '03:45 PM', '05:05 PM', 132, 621.0, 4700.0),
    ('IndiGo', '6E 431', 'Airbus A320neo', 'Nagpur', 'Raipur', '06:20 PM', '07:15 PM', 164, 285.0, 3500.0),
    ('Air India', 'AI 432', 'Airbus A320neo', 'Raipur', 'Bhubaneswar', '08:25 AM', '09:40 AM', 150, 443.0, 4200.0),
    ('Vistara', 'UK 433', 'Airbus A320neo', 'Bhubaneswar', 'Ranchi', '11:00 AM', '12:00 PM', 146, 344.0, 3600.0),
    ('Alliance Air', '9I 434', 'ATR 72-600', 'Ranchi', 'Patna', '02:10 PM', '03:00 PM', 64, 253.0, 3100.0),
    ('IndiGo', '6E 435', 'Airbus A320neo', 'Varanasi', 'Delhi', '07:50 AM', '09:20 AM', 170, 667.0, 4900.0),
    ('Air India', 'AI 436', 'Airbus A321', 'Delhi', 'Varanasi', '05:35 PM', '07:05 PM', 158, 667.0, 5000.0),
    ('Akasa Air', 'QP 437', 'Boeing 737 MAX 8', 'Mumbai', 'Udaipur', '06:25 AM', '07:45 AM', 162, 624.0, 4700.0),
    ('SpiceJet', 'SG 438', 'Boeing 737', 'Udaipur', 'Ahmedabad', '10:15 AM', '11:05 AM', 124, 210.0, 3000.0),
    ('IndiGo', '6E 439', 'Airbus A320neo', 'Ahmedabad', 'Rajkot', '02:10 PM', '03:00 PM', 166, 214.0, 2900.0),
    ('Air India Express', 'IX 440', 'Boeing 737-800', 'Rajkot', 'Surat', '05:25 PM', '06:20 PM', 134, 318.0, 3300.0),
    ('IndiGo', '6E 441', 'Airbus A320neo', 'Surat', 'Mumbai', '08:10 PM', '09:05 PM', 168, 231.0, 3100.0),
    ('Vistara', 'UK 442', 'Airbus A320neo', 'Bangalore', 'Mangalore', '06:20 AM', '07:10 AM', 152, 296.0, 3200.0),
    ('Air India Express', 'IX 443', 'Boeing 737-800', 'Mangalore', 'Kozhikode', '09:25 AM', '10:20 AM', 136, 233.0, 3000.0),
    ('IndiGo', '6E 444', 'Airbus A320neo', 'Kozhikode', 'Kochi', '01:30 PM', '02:15 PM', 164, 154.0, 2600.0),
    ('Air India', 'AI 445', 'Airbus A320neo', 'Hyderabad', 'Visakhapatnam', '07:05 AM', '08:25 AM', 154, 512.0, 4400.0),
    ('IndiGo', '6E 446', 'Airbus A320neo', 'Visakhapatnam', 'Vijayawada', '10:45 AM', '11:35 AM', 170, 301.0, 3300.0),
    ('SpiceJet', 'SG 447', 'Boeing 737', 'Vijayawada', 'Hyderabad', '04:15 PM', '05:10 PM', 128, 265.0, 3200.0),
    ('Vistara', 'UK 448', 'Airbus A320neo', 'Pune', 'Bangalore', '08:00 AM', '09:30 AM', 150, 735.0, 5400.0),
    ('Akasa Air', 'QP 449', 'Boeing 737 MAX 8', 'Bangalore', 'Mumbai', '06:10 PM', '07:55 PM', 166, 842.0, 5800.0),
    ('Air India', 'AI 450', 'Airbus A321', 'Mumbai', 'Kolkata', '09:20 PM', '12:05 AM', 156, 1652.0, 8200.0);
