CREATE TABLE IF NOT EXISTS "user" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS airplane (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    airline VARCHAR(255),
    flight_number VARCHAR(255) UNIQUE,
    aircraft_model VARCHAR(255),
    "start" VARCHAR(255),
    "end" VARCHAR(255),
    departure_time VARCHAR(50),
    arrival_time VARCHAR(50),
    avl_seat INTEGER NOT NULL,
    num_of_km DOUBLE PRECISION NOT NULL,
    price DOUBLE PRECISION NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_airplane_route ON airplane ("start", "end");

CREATE TABLE IF NOT EXISTS booking (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_reference VARCHAR(255) UNIQUE,
    b_start VARCHAR(255),
    b_end VARCHAR(255),
    user_email VARCHAR(255),
    airline VARCHAR(255),
    flight_number VARCHAR(255),
    aircraft_model VARCHAR(255),
    departure_time VARCHAR(50),
    arrival_time VARCHAR(50),
    class_type VARCHAR(50),
    seat_numbers VARCHAR(255),
    b_num_ofseat INTEGER NOT NULL,
    price DOUBLE PRECISION NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_booking_user_email ON booking (user_email);
CREATE INDEX IF NOT EXISTS idx_booking_route ON booking (b_start, b_end);
